services:
  web:
    build:
      dockerfile: Dockerfile.dev
    image: tech_audit
    ports:
      - "3000:3000"
    environment:
      RUBY_DEBUG_NO_RELINE: true
      RUBY_DEBUG_HOST: 0.0.0.0
      RUBY_DEBUG_PORT: 12345
      ESPACE_MEMBRE_DB_URL: postgresql://postgres:dummy@espace-membre-db:5433
      BETA_STANDARDS_YML_PATH: "config/standards-beta.yml"
    volumes:
      - "./:/app"
      - "/app/node_modules"
    depends_on:
      - espace-membre-db
  espace-membre-db:
    image: postgres
    volumes:
      - "./tmp/edb:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 'dummy'
      PGPORT: 5433
