name: ci

on:
  push:
    branches-ignore:
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: standards:latest
          outputs: type=docker,dest=/tmp/standards.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/cache@v4
        name: Cache image and ENV file
        id: standards-docker
        with:
          path: |
            /tmp/standards.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-standards
  lint:
    name: "Linting: Rubocop"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/standards.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-standards
      - run: docker load --input /tmp/standards.tar
      - run: docker run --rm --entrypoint="" standards:latest bin/rubocop -f github
  security-brakeman:
    name: "Security: Brakeman"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/standards.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-standards
      - run: docker load --input /tmp/standards.tar
      - run: docker run --rm --entrypoint="" standards:latest bin/brakeman --no-pager
  unit-tests:
    name: "Unit tests: RSpec"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/standards.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-standards
      - run: docker load --input /tmp/standards.tar
      - run: |
          docker run \
            --network="host" \
            --env-file ./.github/workflows/test.env \
            --rm standards bundle exec rspec
  integration-tests:
    name: "Integration tests: Cucumber"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/standards.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-standards
      - run: docker load --input /tmp/standards.tar
      - run: |
          docker run \
            --network="host" \
            --env-file ./.github/workflows/test.env \
            --rm standards bundle exec cucumber
